# Generated by Django 5.2.8 on 2026-04-26 03:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('administrateur', 'Administrateur')], default='etudiant', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('objectif', models.TextField()),
                ('description', models.TextField()),
                ('date_publication', models.DateField()),
                ('ressource', models.FileField(blank=True, null=True, upload_to='ressources/')),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
            },
            bases=('eLearning.user',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Enseignant',
            },
            bases=('eLearning.user',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('etablissement', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Étudiant',
            },
            bases=('eLearning.user',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=20)),
                ('note_max', models.FloatField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='eLearning.cours')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='eLearning.enseignant'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateField()),
                ('moyen_paiement', models.CharField(max_length=50)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eLearning.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=100)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='eLearning.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='eLearning.etudiant')),
            ],
        ),
    ]
