# Generated by Django 5.2.8 on 2026-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0003_cours_est_premium_cours_prix_inscription_est_paye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='quiz_media/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='texte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
