# Generated by Django 5.2.8 on 2026-04-28 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0004_question_media_alter_question_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
