# Generated by Django 5.2.8 on 2026-04-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0005_alter_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='fichier_quiz',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/'),
        ),
    ]
