# Generated by Django 5.2.8 on 2026-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0006_quiz_fichier_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionvisio',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AddField(
            model_name='sessionvisio',
            name='duree',
            field=models.IntegerField(default=60, help_text='Durée en minutes'),
        ),
        migrations.AddField(
            model_name='sessionvisio',
            name='est_termine',
            field=models.BooleanField(default=False),
        ),
    ]
