# Generated by Django 6.0.5 on 2026-05-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0008_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=50),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
