# Generated by Django 6.0.4 on 2026-05-09 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type_correction',
            field=models.CharField(choices=[('manuelle', 'Correction Manuelle'), ('auto', 'Correction Automatique par IA')], default='manuelle', max_length=20),
        ),
        migrations.CreateModel(
            name='SoumissionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('fichier_reponse', models.FileField(blank=True, null=True, upload_to='reponses_quizzes/')),
                ('reponses_qcm', models.TextField(blank=True, null=True)),
                ('est_corrige', models.BooleanField(default=False)),
                ('note_obtenue', models.FloatField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('corrige_par_ia', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='eLearning.etudiant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='eLearning.quiz')),
            ],
        ),
    ]
