# Generated by Django 6.0.4 on 2026-05-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0011_quiz_type_correction_soumissionquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
