# Generated by Django 6.0.4 on 2026-05-09 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0012_user_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField()),
                ('lien_externe', models.URLField(blank=True, null=True)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='livres_couvertures/')),
                ('est_premium', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='lien_youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AchatLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres_achetes', to='eLearning.etudiant')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheteurs', to='eLearning.livre')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSimulee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_transaction', models.CharField(choices=[('achat_cours', 'Achat de Cours'), ('achat_livre', 'Achat de Livre'), ('recharge', 'Recharge de Compte')], max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_simulees', to='eLearning.etudiant')),
            ],
        ),
    ]
