# Generated by Django 6.0.4 on 2026-05-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0013_livre_cours_lien_youtube_etudiant_solde_achatlivre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsimulee',
            name='type_transaction',
            field=models.CharField(choices=[('achat_cours', 'Achat de Cours'), ('achat_livre', 'Achat de Livre'), ('achat_chapitre', 'Achat de Chapitre'), ('recharge', 'Recharge de Compte')], max_length=20),
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('est_premium', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ressource', models.FileField(blank=True, null=True, upload_to='chapitres_ressources/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='eLearning.cours')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ChapitreDebloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deblocage', models.DateTimeField(auto_now_add=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deblocages', to='eLearning.chapitre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres_debloques', to='eLearning.etudiant')),
            ],
            options={
                'verbose_name': 'Chapitre Débloqué',
                'verbose_name_plural': 'Chapitres Débloqués',
                'unique_together': {('etudiant', 'chapitre')},
            },
        ),
    ]
