# Generated by Django 6.0.4 on 2026-05-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0014_alter_transactionsimulee_type_transaction_chapitre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='lien_youtube',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
