# Generated by Django 6.0.4 on 2026-05-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0016_logactivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cours_images/'),
        ),
    ]
