# Generated by Django 6.0.4 on 2026-05-31 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0017_cours_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='ressources_cours/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_annexes', to='eLearning.cours')),
            ],
            options={
                'verbose_name': 'Ressource du Cours',
                'verbose_name_plural': 'Ressources du Cours',
            },
        ),
    ]
