# Generated by Django 6.0.5 on 2026-05-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0019_module_chapitre_module_ressourcechapitre'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
