# Generated by Django 6.0.5 on 2026-06-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0020_chapitre_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='titre_module',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
