# Generated by Django 6.0.5 on 2026-06-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0021_cours_titre_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choix',
            name='texte',
            field=models.TextField(),
        ),
    ]
