# Generated by Django 6.0.5 on 2026-06-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0022_alter_choix_texte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapitreVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='eLearning.chapitre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres_vus', to='eLearning.etudiant')),
            ],
            options={
                'verbose_name': 'Chapitre Vu',
                'verbose_name_plural': 'Chapitres Vus',
                'unique_together': {('etudiant', 'chapitre')},
            },
        ),
    ]
