# Generated by Django 6.0.5 on 2026-06-07 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0023_chapitrevu'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module auquel ce quiz est rattaché (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='eLearning.module'),
        ),
    ]
