# Generated by Django 6.0.5 on 2026-06-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0024_quiz_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='est_premium',
            field=models.BooleanField(default=False),
        ),
    ]
