# Generated by Django 6.0.5 on 2026-06-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0026_paiementpaygate'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementpaygate',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_paygate', to='eLearning.cours'),
        ),
        migrations.AddField(
            model_name='paiementpaygate',
            name='type_paiement',
            field=models.CharField(choices=[('recharge', 'Recharge du portefeuille'), ('achat_cours', 'Achat de cours premium')], default='recharge', max_length=20),
        ),
    ]
